### ISSUE TITLE
Replace keccak256 with blake2

### ISSUE THREAD

**Issue by caesarchad** [bitconch/bitconch-core#11]
[Blake2 Intro Slide](https://blake2.net/acns/slides.html)
[Blake2 Introduced by one of the Author](https://crypto.stackexchange.com/questions/31674/what-advantages-does-keccak-sha-3-have-over-blake2)
@luhuimao 
 please do research on Keccak256 Keccak512
 under crypto/to/crypto.go, ch, check where they are used, and we are going to replace keccak256/Keccak512 with th blake at [golang.org/x/crypto/blake2b](golang.org/x/crypto/blake2b)

### Sample Codes

```golang

import (
	"hash"

	"golang.org/x/crypto/blake2b"
)

// NewBlake2b return blake2b-256 hash.
func NewBlake2b() hash.Hash {
	hash, _ := blake2b.New256(nil)
	return hash
}

// Blake2b computes blake2b-256 checksum for given data.
func Blake2b(data ...[]byte) (b32 Bytes32) {
	hash := NewBlake2b()
	for _, b := range data {
		hash.Write(b)
	}
	hash.Sum(b32[:0])
	return
}


```
#### golang src files use sha3.NewKeccak256, total 21 files

#no | go file | package | others 
--- | --- | --- | ---
1 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\common\types.go 
2 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\consensus\buffett\buffett.go
3 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\consensus\clique\clique.go
4 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\consensus\ethash\algorithm.go
5 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\core\rawdb\accessors_chain_test.go
6 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\core\types\block.go
7 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\crypto\crypto.go
8 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\eth\downloader\statesync.go
9 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\p2p\discv5\net.go
10 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\p2p\enr\idscheme.go
11 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\p2p\rlpx_test.go
12 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\p2p\rlpx.go
13 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\p2p\server_test.go
14 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\swarm\bmt\bmt_test.go
15 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\swarm\bmt\bmt.go
16 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\swarm\storage\chunker_test.go
17 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\swarm\storage\encryption\encryption_test.go
18 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\swarm\storage\hasherstore.go
19 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\swarm\storage\types.go
20 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\tests\state_test_util.go
21 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\trie\hasher.go 

#### golang src files use sha3.NewKeccak512, total 2 files

#no | go file | package | others 
--- | --- | --- | ---
1 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\consensus\ethash\algorithm.go
2 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\crypto\crypto.go

    
#### golang src files use crypto.Keccak256, total 42 files

#no | go file | package | others 
--- | --- | --- | ---
1 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\accounts\abi\abi_test.go | accounts
2 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\accounts\abi\event.go | accounts
3 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\accounts\abi\method.go | accounts
4 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\accounts\keystore\keystore_passphrase.go | accounts
5 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\accounts\keystore\presale.go | accounts
6 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\cmd\clef\main.go | cmd
7 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\cmd\ethkey\utils.go | cmd
8 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\consensus\buffett\buffett.go | consensus
9 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\consensus\clique\clique.go | consensus
10 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\consensus\ethash\algorithm.go | consensus
11 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\contracts\chequebook\cheque.go | contracts
12 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\core\bloombits\matcher.go | core
13 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\core\state\state_object.go | core
14 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\core\types\bloom9_test.go | core
15 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\core\types\bloom9.go | core | core
16 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\core\types\transaction_signing.go | core
17 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\core\vm\contracts.go | core
18 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\core\vm\instructions.go | core
19 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\core\vm\runtime\runtime.go | core
20 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\internal\ethapi\api.go | internal
21 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\les\handler_test.go | les
22 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\les\protocol.go | les
23 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\les\request_test.go | les
24 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\light\nodeset.go | light
25 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\light\trie.go | light
26 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\node\api.go | node
27 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\p2p\discover\udp.go | p2p
28 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\p2p\discv5\udp.go | p2p
29 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\p2p\enr\idscheme.go | p2p
30 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\p2p\rlpx_test.go | p2p
31 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\p2p\rlpx.go | p2p
32 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\signer\core\api.go | signer
33 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\swarm\network\protocol.go | swarm
34 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\tests\vm_test_util.go | tests
35 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\trie\proof_test.go | trie
36 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\trie\proof.go | trie
37 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\trie\secure_trie_test.go | trie
38 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\trie\trie_test.go | trie
39 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\whisper\whisperv5\envelope.go | whisperv5
40 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\whisper\whisperv5\message.go | whisperv5
41 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\whisper\whisperv6\envelope.go | whisperv5
42 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\whisper\whisperv6\message.go | whisperv5

#### golang src files use crypto.Keccak512, total 1 files

#no | go file | package | others 
--- | --- | --- | ---
1 | C:\Users\Jacky\gopath\src\github.com\Bitconch\BUS\consensus\ethash\algorithm.go

**Comment by caesarchad** [comment]
@luhuimao 
My thoughts, create a new go file containing the above function(modify if necessary) and replace all occurrences of existing keccak256/512.

**Comment by luhuimao** [comment]
@caesarchad 
After my investigation, Blake2 offers better security and performance compared to  keccak256,  reasons as below:
- SHA256 was based on SHA1 (which is weak). BLAKE was based on
ChaCha20 (which is strong).
- SHA256 has realistically feasible attacks against 31 out of 64
rounds. BLAKE2 has no feasible attacks against more than 2 out of 10
(BLAKE2s) or 2 out of 12 (BLAKE2b) rounds.
- BLAKE2 has security features which could be useful for us, such as
protection against length-extension, a standard method of keying,
"personalization tags" to guarantee domain separation, etc.
- BLAKE2 is more efficient than SHA256 in software on most
platforms. For example, on ARM chips, it is usually about twice as
efficient as SHA256 when hashing 64 bytes.
- BLAKE2 is the de facto standard hash function used by all of the
skilled symmetric cryptographers working on things like Password
Hashing Competition, new Proofs-of-Work such as Equihash,
etc. Whatever Proof-of-Work function we choose, it'll probably turn
out to come defined to use BLAKE2.

**Comment by caesarchad** [comment]
@luhuimao excellent work!
I have updated the code https://github.com/Bitconch/BUS/issues/11#issuecomment-418029397
, will do some unit test to check.

**Comment by luhuimao** [comment]
golang src files use sha3.NewKeccak256 addition:

|#No|Go file|package|others|
|:----|:----|:----|:----|
|1|accounts\abi\abi_test.go|||
|2|accounts\abi\bind\topics.go|||
|3|accounts\abi\event.go|||
|4|accounts\abi\event_test.go|||
|5|accounts\abi\method.go|||
|6|accounts\keystore\keystore_passphrase.go|||
|7|cmd\clef\main.go|||
|8|cmd\ethkey\utils.go|||
|9|cmd\utils\cmd.go|||
|10|contracts\chequebook\cheque.go|||
|11|contracts\ens\ens.go|||
|12|contracts\ens\ens_test.go|||
|13|core\state\statedb.go|||
|14|core\state\state_object.go|||
|15|core\state\state_test.go|||
|16|core\state\sync_test.go|||
|17|core\types\bloom9.go|||
|18|core\types\bloom9_test.go|||
|19|core\types\transaction_signing.go|||
|20|core\vm\contracts.go|||
|21|core\vm\evm.go|||
|22|core\vm\instructions.go|||
|23|core\vm\runtime\runtime.go|||
|24|eth\handler_test.go|||
|25|internal\ethapi\api.go|||
|26|les\handler_test.go|||
|27|les\protocol.go|||
|28|les\request_test.go|||
|29|light\nodeset.go|||
|30|light\odr_util.go|||
|31|light\trie.go|||
|32|node\api.go|||
|33|p2p\discover\database.go|||
|34|p2p\discover\node.go|||
|35|p2p\discover\table.go|||
|36|p2p\discover\table_test.go|||
|37|p2p\discover\udp.go|||
|38|p2p\discover\udp_test.go|||
|39|p2p\discv5\database.go|||
|40|p2p\discv5\net_test.go|||
|41|p2p\discv5\node.go|||
|42|p2p\discv5\ticket.go|||
|43|p2p\discv5\udp.go|||
|44|p2p\discv5\udp_test.go|||
|45|signer\core\api.go|||
|46|swarm\api\config.go|||
|47|swarm\network\protocol.go|||
|48|tests\vm_test_util.go|||
|49|trie\proof.go|||				
|50|trie\proof_test.go|||
|51|trie\secure_trie_test.go|||	
|52|trie\trie.go|||
|53|trie\trie_test.go|||
|54|whisper\mailserver\server_test.go|||
|55|whisper\whisperv5\api.go|||	
|56|whisper\whisperv5\envelope.go|||		
|57|whisper\whisperv5\filter.go|||		
|58|whisper\whisperv5\filter_test.go|||
|59|whisper\whisperv5\message.go|||
|60|whisper\whisperv6\api.go|||	
|61|whisper\whisperv6\envelope.go|||
|62|whisper\whisperv6\filter.go|||
|63|whisper\whisperv6\filter_test.go|||
|64|whisper\whisperv6\message.go|||

**Comment by caesarchad** [comment]
@luhuimao 
Push to BUS005 branch.
