### ISSUE TITLE
Fix node crash issue.

### ISSUE THREAD

**Issue by caesarchad** [bitconch/bitconch-core#120]
#### Expected behavior
Keep running and running

#### Actual behaviour
Report unable to allocate memory error 

#### Steps to reproduce the behavior
Run the service for 24 hours

#### Backtrace

````
Jul 13 10:44:55 node3 bash[13636]: thread 'soros-banking-stage-tx' panicked at 'failed to map the data file: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', src/libcore/result.rs:999:5
````

**Comment by luhuimao** [comment]
after downgrade rust to 1.35 , issue 'allocate memory error“ has gone.

**Comment by luhuimao** [comment]
@caesarchad Now that hitting another issue(maybe not  an issue, the service won't crashed but stop served, get "internal error" when launch a drone request from front-end.) " next leader not found” in soros-leader.service

**Comment by luhuimao** [comment]
Update：restart the leader service will fix "no next leader found" issue. @caesarchad

**Comment by luhuimao** [comment]
update: Still crashed under rust 1.35, downgrade to 1.34 and rebuild and start all the service, monitor and see what happens .

**Comment by caesarchad** [comment]
After downgrade to 1.34, the issue still persists.
