### ISSUE TITLE
Technical Weekly Report (Oct 22)

### ISSUE THREAD

**Issue by caesarchad** [bitconch/bitconch-core#137]
| # | Components  | Contents  | Assignees  | Remark  |
|---|---|---|---|---|
| 1  | web3j | upgrade transaction fees |  ben,caesar |   |
|  2 |  docker |  repack core codes and published to dockerhub |  brian,caesar |   |
|  3 | webwallet  | upgrading web wallet to 1.2 release.#webwallet Redesign the layout, adding button "account info" , "send transaction", " create token", "send token" at top bar, click in dirrerent button to controll which feature being display.Add bitonch logo at the top. Redesign the bottons, textbox more humanable.web wallet was deployed  | ben,caesar  |   |
|  4 | core  | sperating rust/go code, preparing to migrate 1.2  | caesar  |   |
| 5 | dapp | creating a blockchain based state app using javascript for bitconch chain.Working DApp sample (Gobang) 1. Prepare the environment and test codes functionality. 2. Update the compiler process. | caesar,brian | |
| 6 | documentation | Migrating documentations(whitepaper, refernce, and guides to [bitconch.readdocs.io](https://bitconch.readthedocs.io/en/latest/) |caesar,cara | |

**Comment by cc-cara** [comment]
1.Collect relevant documents;
2.Setup the email services

**Comment by luhuimao** [comment]
#webwallet Redesign the layout, adding button "account info" ,  "send transaction", " create token",  "send token"  at top bar, click in dirrerent button to controller which feature being display. 
Add bitonch logo at the top.  Redesign the bottons, textbox more humanable.  
web  wallet was deployed, check it out http://47.244.209.112:8965

**Comment by aya015757881** [comment]
Objective:
    To get both the Javascript code of solana's tic-tac-toe and the Rust code of Bitconch's morgan run and interact with each other.

Status on Oct.17th 2019:
    Linux environment for the running of the Rust code is being prepared.


Status on Oct.18th 2019:
    The Rust code runs. The Javascript code of tic-tac-toe needs some revisions of names for the adaption to Bitconch's web3.js code to get able to run.


Status on Oct.19th 2019:
        The build process for tic-tac-toe fails due to the termination of the execution of the bash file "install.sh". To be specific, the bash file terminates at an attempt to get into a directory which does not exist.


Status on Oct.20th 2019:
    The build process for tic-tac-toe includes downloading a series of compiler tools. Nevertheless, the download is suspended by the unstable network.


Status on Oct.21st 2019:
    The tic-tac-toe's code contains some C source files. And the linker called lld has some trouble generating the .so files from the compiled object files.

**Comment by cc-cara** [comment]
1. Overhaul the documentation structure, and composing documents including
    installation instructions and developer guide.
2. Setup new domain bitconch.readdocs.io
3. Other miscellaneous adminstration tasks including web host/domain registration/email maintannce.

**Comment by cc-cara** [comment]
1.在web3j上更新关于交易费用的代码；（ben,caesar）
2.重新打包docker的核心代码并发布到dockerhub；（caesar,brian）
3.将网页版钱包迭代至1.2版本（ben,caesar）
4.将网页版钱包的页面重新排版。在顶部栏上添加“账户信息”、“发送交易”；“创建代币”按钮，点击不同的按钮来选择所需的功能；（ben,caesar）
5.在钱包顶部添加bitconch的logo；（ben,caesar）
6.重新设计按钮和文本框，使之更简洁美观、且更人性化；（ben,caesar）
7.部署网页版钱包；（ben,caesar）
8.更新rust/go 代码，准备将版本迭代至1.2版本；（caesar）
9.基于区块链的状态应用上用javascript 创建bitconch链；（caesar,brian）
10.研究DApp示例(五子棋)：①准备环境并测试代码的功能；②更新编译器进程；（caesar,brian）
11.迁移文档。将白皮书、参考资料和指南等文档迁移至bitcon .ReadtheDocs .io上。（caesar,cara）
