### ISSUE TITLE
Technical Weekly Report (Oct 28) 

### ISSUE THREAD

**Issue by caesarchad** [bitconch/bitconch-core#138]
| # | Components  | Contents  | Assignees  | Remark  |
|---|---|---|---|---|
| 1  | web3j |  |  ben,caesar |   |
|  2 |  docker |  Create a docker image of morgan and push it to dockerhub. Still Testing  |  brian,caesar |   |
|  3 | webwallet  |  adding a new feature to Asset Manage , let user to add a new token account , then others can transfer token to him.Make all the button && icon && layout in same style.Display enterprise information at the bottom. | ben,caesar  |   |
|  4 | core  | sperating rust/go code, preparing to migrate 1.2  | caesar  |   |
| 5 | dapp |   | caesar,brian | |
| 6 | documentation | 1.Optimize document framework 2.Import logo in SVG format of Bitconch 3.Deploy test wallet on testwallet.dltfoundry.org  |caesar,cara | |

**Comment by aya015757881** [comment]
Create a docker image of morgan and push it to dockerhub.

**Comment by cc-cara** [comment]
1.Optimize document framework
2.Import logo in SVG format of Bitconch
3.Deploy nginx on the server with the help of caesar

**Comment by luhuimao** [comment]
#web wallet
1. adding a new feature to Asset Manage , let user to add a new token account , then others can transfer token to him.
2. Make all the button && icon && layout in sane style.
3. Display enterprise information at the bottom.

**Comment by cc-cara** [comment]
1.创建Morgan的docker 镜像并将代码提交到dockerhub上（测试中）；（brian,caesar）
2.在资产管理中增加新功能，使客户能创建新的代币账户，然后就可以与其他用户进行转账交易；（ben,caesar）
3.将钱包所有的按钮、图标和布局的格式统一化；（ben,caesar）
4.将公司信息显示在钱包底部；（ben,caesar）
5.更新rust/go 代码，准备将版本迭代至1.2版本；（caesar）
6.优化ReadtheDocs上文档的框架；并将Bitcon SVG格式的logo导入文档；caesar,cara
7.在testwallet.dltfoundry.org上部署测试钱包。caesar,cara
