### ISSUE TITLE
Technical Weekly Report (Feb 4th - Feb 14th)

### ISSUE THREAD

**Issue by caesarchad** [bitconch/bitconch-core#87]
**pre-testnet-release**
You can check the codes from this url: https://github.com/bitconch/bus/releases
This is the pre test net release, we have create several tools to implement the bitconch whitepaper.
1. Configuration tools under cmd folder
2. Genesis tools under cmd folder
3. Fullnode and its configuration tools under cmd folder
4. Scripts to setup env, precompile, compile and build.
5. You can go to release tab on github code, download the source codes and try to test the code yourself.

Current and next step
A fully functional wallet cli, facuet, block explore, and lot more. Which will be released very soon.

**Comment by luhuimao** [comment]
Doing the following research about smart contract: 

1. How to make smart contract can write in most any language? 
2. How to speed up the smart contract execution process
